[alias]
# Run using: 'cargo test-none'
test-none = [ "test", "--no-default-features"]
test-serde = "test --features serde"
test-storage = "test --features storage"

check-none = [ "check", "--no-default-features"]
check-8 = [ "check", "--no-default-features", "--features", "eight_motors"]
check-serde = [ "check", "--no-default-features", "--features", "serde"]
check-storage = [ "check", "--no-default-features", "--features", "serde", "storage"]

# Continuous Integration
ci = "run --package xtask --bin xtask"
# MSRV
check-msrv = "run --package xtask --bin xtask -- check-msrv"
